// Fetch Hoa Sen Home listed retail prices (tôn Hoa Sen category) and write
// src/data/hoa-sen-reference.ts as a per-family price summary.
//
// Run: node scripts/fetch-hoasen.mjs
// Exit 0 = file written (content identical if prices unchanged).
// Exit 1 = fetch/sanity failure — file NOT touched, do not publish.
//
// Source: public Magento GraphQL API of hoasenhome.vn (anonymous default
// region). Prices are Hoa Sen Home's listed retail prices (giá niêm yết),
// used on /ton-hoa-sen/ as an attributed market reference only — this script
// must never write to src/data/prices.ts (Hà Lan's own selling prices).
import fs from 'node:fs';

const ENDPOINT = 'https://hoasenhome.vn/graphql';
// category_uid "Mw==" = base64("3") — the "Tôn Hoa Sen" category
const QUERY = `query { products(pageSize: 100, currentPage: 1, filter: {category_uid: {eq: "Mw=="}}, sort: {position: ASC}) { total_count items { name price_range { minimum_price { final_price { value } } } } } }`;

const FAMILIES = [
  { name: 'Tôn cách nhiệt PU', test: (n) => n.startsWith('Tôn cách nhiệt PU') },
  { name: 'Tôn lạnh màu', test: (n) => n.startsWith('Tôn lạnh màu') },
  { name: 'Tôn lạnh', test: (n) => n.startsWith('Tôn lạnh') },
  { name: 'Tôn Hoa Sen Gold', test: (n) => /gold/i.test(n) },
];
// Sanity bounds (đ/m): outside this range means a parse or source change — abort.
const MIN_PRICE = 20_000;
const MAX_PRICE = 300_000;

// NOTE: set process.exitCode instead of calling process.exit() — forcing exit
// while undici's sockets are open crashes libuv on Windows (bogus exit code).
const res = await fetch(`${ENDPOINT}?query=${encodeURIComponent(QUERY)}`);
if (!res.ok) {
  console.error(`fetch failed: HTTP ${res.status}`);
  process.exitCode = 1;
} else {
  main(await res.json());
}

function main(body) {
const items = body?.data?.products?.items ?? [];

const groups = new Map(FAMILIES.map((f) => [f.name, []]));
let unmatched = 0;
for (const it of items) {
  const price = it?.price_range?.minimum_price?.final_price?.value;
  if (typeof price !== 'number') continue;
  const fam = FAMILIES.find((f) => f.test(it.name));
  if (fam) groups.get(fam.name).push(price);
  else unmatched++;
}

const rows = FAMILIES.map((f) => {
  const ps = groups.get(f.name);
  return ps.length
    ? { family: f.name, variants: ps.length, min: Math.min(...ps), max: Math.max(...ps) }
    : null;
}).filter(Boolean);

// Sanity rails: refuse to publish thin or implausible data.
const allPrices = rows.flatMap((r) => [r.min, r.max]);
if (
  rows.length < 3 ||
  items.length < 20 ||
  unmatched > items.length / 4 ||
  allPrices.some((p) => p < MIN_PRICE || p > MAX_PRICE)
) {
  console.error(
    `sanity check failed: families=${rows.length} items=${items.length} unmatched=${unmatched} prices=${JSON.stringify(allPrices)}`
  );
  process.exitCode = 1;
  return;
}

const today = new Date().toLocaleDateString('vi-VN', {
  day: '2-digit',
  month: '2-digit',
  year: 'numeric',
});

const ts = `// GENERATED by scripts/fetch-hoasen.mjs — do not edit by hand.
// Giá bán lẻ niêm yết của Hoa Sen Home (hoasenhome.vn), dùng làm giá tham khảo
// thị trường trên /ton-hoa-sen/. KHÔNG phải giá bán của Hà Lan (xem prices.ts).

export interface HoaSenFamily {
  family: string;
  variants: number; // số quy cách (màu × độ dày)
  min: number; // đ/m
  max: number; // đ/m
}

export const hoaSenReference = {
  updated: '${today}',
  source: 'Hoa Sen Home (hoasenhome.vn) — giá bán lẻ niêm yết',
  rows: ${JSON.stringify(rows, null, 2).replace(/"([a-z]+)":/g, '$1:').replace(/"/g, "'")} as HoaSenFamily[],
};
`;

const OUT = 'src/data/hoa-sen-reference.ts';
const prev = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
// Only the date differs when prices are unchanged — compare without the date
// line so an unchanged market day produces no git diff at all.
const stripDate = (s) => s.replace(/updated: '[^']*'/, '');
if (stripDate(prev) === stripDate(ts)) {
  console.log(`unchanged (${rows.length} families, ${items.length} items) — file not rewritten`);
  return;
}
fs.writeFileSync(OUT, ts);
console.log(`written ${OUT}: ${rows.length} families from ${items.length} items, updated ${today}`);
}
