// GENERATED by scripts/fetch-hoasen.mjs — do not edit by hand.
// Giá bán lẻ niêm yết của Hoa Sen Home (hoasenhome.vn), dùng làm giá tham khảo
// thị trường trên /ton-hoa-sen/. KHÔNG phải giá bán của Hà Lan (xem prices.ts).

export interface HoaSenFamily {
  family: string;
  variants: number; // số quy cách (màu × độ dày)
  min: number; // đ/m
  max: number; // đ/m
}

export const hoaSenReference = {
  updated: '22/07/2026',
  source: 'Hoa Sen Home (hoasenhome.vn) — giá bán lẻ niêm yết',
  rows: [
  {
    family: 'Tôn cách nhiệt PU',
    variants: 32,
    min: 180400,
    max: 215600
  },
  {
    family: 'Tôn lạnh màu',
    variants: 32,
    min: 91850,
    max: 141350
  },
  {
    family: 'Tôn lạnh',
    variants: 4,
    min: 97900,
    max: 132000
  },
  {
    family: 'Tôn Hoa Sen Gold',
    variants: 17,
    min: 149600,
    max: 231000
  }
] as HoaSenFamily[],
};
