// GENERATED by scripts/fetch-hoasen.mjs — do not edit by hand.
// Giá bán lẻ niêm yết của Hoa Sen Home (hoasenhome.vn), dùng làm giá tham khảo
// thị trường trên /ton-hoa-sen/. KHÔNG phải giá bán của Hà Lan (xem prices.ts).

export interface HoaSenFamily {
  family: string;
  variants: number; // số quy cách (màu × độ dày)
  min: number; // đ/m
  max: number; // đ/m
}

export const hoaSenReference = {
  updated: '20/07/2026',
  source: 'Hoa Sen Home (hoasenhome.vn) — giá bán lẻ niêm yết',
  rows: [
  {
    family: 'Tôn cách nhiệt PU',
    variants: 32,
    min: 181500,
    max: 216700
  },
  {
    family: 'Tôn lạnh màu',
    variants: 32,
    min: 92400,
    max: 142450
  },
  {
    family: 'Tôn lạnh',
    variants: 4,
    min: 98450,
    max: 133100
  },
  {
    family: 'Tôn Hoa Sen Gold',
    variants: 17,
    min: 150700,
    max: 232100
  }
] as HoaSenFamily[],
};
