// GENERATED by scripts/fetch-hoasen.mjs — do not edit by hand.
// Giá bán lẻ niêm yết của Hoa Sen Home (hoasenhome.vn), dùng làm giá tham khảo
// thị trường trên /ton-hoa-sen/. KHÔNG phải giá bán của Hà Lan (xem prices.ts).

export interface HoaSenFamily {
  family: string;
  variants: number; // số quy cách (màu × độ dày)
  min: number; // đ/m
  max: number; // đ/m
}

export const hoaSenReference = {
  updated: '11/09/2026',
  source: 'Hoa Sen Home (hoasenhome.vn) — giá bán lẻ niêm yết',
  rows: [
  {
    family: 'Tôn cách nhiệt PU',
    variants: 32,
    min: 179300,
    max: 214500
  },
  {
    family: 'Tôn lạnh màu',
    variants: 32,
    min: 94050,
    max: 144100
  },
  {
    family: 'Tôn lạnh',
    variants: 4,
    min: 100100,
    max: 135300
  },
  {
    family: 'Tôn Hoa Sen Gold',
    variants: 17,
    min: 152900,
    max: 231000
  }
] as HoaSenFamily[],
};
